### ISSUE TITLE
TagBot is not creating GithubReleases

### ISSUE THREAD

**Issue by CarloLucibello** [fhs/NPZ.jl#59]
v0.42 and v0.43 hare available in the JuliaRegistries but TagBot didn't create the corresponding GitHub release. 
It is the first time I see this behavior and I don't know what is causing it.
According to the [TagBot readm](https://github.com/JuliaRegistries/TagBot) no action besides creating the `TagBot.yml` should be required.

**Comment by fhs** [comment]
I see the following in the Actions logs. I've removed the ssh key from the config. Let's see if this fixes it.
I think the ssh key was added for pushing the documentation to the repo, but we should remove documentation generation and just link to [juliahub docs](https://docs.juliahub.com/NPZ/TV7Kn/0.4.3/).
```
Processing version v0.4.3 (b83fddf2d773936b531e5f355d4f3f1d2738a5d6)
Generating changelog for version v0.4.3 (b83fddf2d773936b531e5f355d4f3f1d2738a5d6)
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 533, in create_release
    self._git.create_tag(version, sha, log)
  File "/root/tagbot/action/git.py", line 107, in create_tag
    self.command("push", "origin", version)
  File "/root/tagbot/action/git.py", line 71, in command
    raise Abort(f"Git command '{cmd}' failed")
tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_ovsviiru push origin v0.4.3' failed

Response (200): {
  "status": "Submitted error report"
}
```
